spring:
  application:
    name: intershop
  datasource:
    url: jdbc:h2:mem:blogdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
