spring:
  application:
    name: intershop
  r2dbc:
    url: r2dbc:h2:mem:///shopdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    io.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG
